Added lualib50 check to configure.ac.

diff --git a/module_00/configure b/module_00/configure
--- a/module_00/configure
+++ b/module_00/configure
@@ -5115,6 +5115,80 @@ fi
 fi
 
 
+echo "$as_me:$LINENO: checking for luaopen_table in -llualib50" >&5
+echo $ECHO_N "checking for luaopen_table in -llualib50... $ECHO_C" >&6
+if test "${ac_cv_lib_lualib50_luaopen_table+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-llualib50  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char luaopen_table ();
+int
+main ()
+{
+luaopen_table ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_lualib50_luaopen_table=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_lualib50_luaopen_table=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_lualib50_luaopen_table" >&5
+echo "${ECHO_T}$ac_cv_lib_lualib50_luaopen_table" >&6
+if test $ac_cv_lib_lualib50_luaopen_table = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBLUALIB50 1
+_ACEOF
+
+  LIBS="-llualib50 $LIBS"
+
+else
+  \
+
 echo "$as_me:$LINENO: checking for luaopen_table in -llualib" >&5
 echo $ECHO_N "checking for luaopen_table in -llualib... $ECHO_C" >&6
 if test "${ac_cv_lib_lualib_luaopen_table+set}" = set; then
@@ -5188,8 +5262,10 @@ _ACEOF
 
 else
   \
-	echo "You need to install the lualib library."
-	 exit -1
+		echo "You need to install the lualib library."
+		 exit -1
+fi
+
 fi
 
 
